AWSTemplateFormatVersion: "2010-09-09"
Description: "Fluxo: Usuario -> S3 -> Lambda -> EC2 (com EBS) -> Usuario"

Resources:
  # 1. Bucket S3
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-dio-santander

  # 2. Bucket policy permitindo Lambda ler o código
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::203102861496:role/SuaLambdaExecutionRole
            Action:
              - s3:GetObject
            Resource: !Sub "${MyS3Bucket.Arn}/*"

  # 3. Função Lambda
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      Role: arn:aws:iam::203102861496:role/SuaLambdaExecutionRole
      Code:
        S3Bucket: code-bucket
        S3Key: lambda-code.zip
      Environment:
        Variables:
          BUCKET_NAME: !Ref MyS3Bucket

  # 4. Permissão Lambda para S3
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt MyS3Bucket.Arn
    DependsOn:
      - MyLambdaFunction
      - MyS3Bucket

  # 5. Security Group para EC2
  MyEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso ao EC2
      VpcId: vpc-00a487a5fd375b79e
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # 6. Instância EC2
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c5204531f799e0c6
      KeyName: my-key-pair
      SecurityGroupIds:
        - !Ref MyEC2SecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 8

  # 7. Volume EBS extra
  MyEBSVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt MyEC2Instance.AvailabilityZone
      Size: 20
      VolumeType: gp2

  # 8. Anexar volume EBS
  MyEBSAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyEC2Instance
      VolumeId: !Ref MyEBSVolume
      Device: /dev/sdh
